apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
    verbs: ["create", "delete", "update", "patch", "get", "list"]
    resources:
      - group: ""
        resources: ["pods", "secrets", "configmaps", "serviceaccounts", "roles", "rolebindings"]
  - level: RequestResponse
    verbs: ["create"]
    resources:
      - group: ""
        resources: ["pods/exec"]
  - level: Metadata
    resources:
      - group: ""
        resources: ["*"]
      - group: "apps"
        resources: ["*"]
      - group: "rbac.authorization.k8s.io"
        resources: ["*"]
      - group: "networking.k8s.io"
        resources: ["*"]
      - group: "batch"
        resources: ["*"]
      - group: "autoscaling"
        resources: ["*"]