apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-hostpath
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: nginx
      image: nginx
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 101
      volumeMounts:
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
        - name: logs
          mountPath: /var/log/nginx
  volumes:
    - name: data
      emptyDir: {}
    - name: tmp
      emptyDir: {}
    - name: cache
      emptyDir: {}
    - name: run
      emptyDir: {}
    - name: logs
      emptyDir: {}